import json
from datetime import datetime
from typing import Dict, Any, List, Tuple
from tools.ComparisonData import ComparisonData


class ComparisonReporter:
    """Report generation class for ontology comparisons
    
    This class generates comprehensive markdown reports and JSON summaries
    for ontology comparisons, including executive summaries, detailed metrics
    comparisons, and key findings.
    """
    
    def __init__(self):
        """Initialize reporter"""
        pass
    
    def generate_report(self, comparison_data: ComparisonData, output_path: str) -> None:
        """Generate complete comparison report as README.md
        
        Args:
            comparison_data: ComparisonData object containing all comparison data
            output_path: Directory path where README.md will be saved
        """
        readme_path = f"{output_path}/README.md"
        
        with open(readme_path, 'w', encoding='utf-8') as f:
            # Write header
            self._write_header(f, comparison_data)
            
            # Write executive summary
            self._write_executive_summary(f, comparison_data)
            
            # Write characteristics comparison
            self._write_characteristics_section(f, comparison_data)
            
            # Write metrics comparison
            self._write_metrics_section(f, comparison_data)
            
            # Write subcharacteristics comparison
            self._write_subcharacteristics_section(f, comparison_data)
            
            # Write key findings
            self._write_key_findings(f, comparison_data)
            
            # Write footer
            f.write("\n---\n\n")
            f.write("*Generated by OQuaRE Metrics Comparison Tool*\n")
    
    def _write_header(self, file_handle, comparison_data: ComparisonData) -> None:
        """Write report header with basic information
        
        Args:
            file_handle: Open file handle for writing
            comparison_data: ComparisonData object
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        file_handle.write("# OQuaRE Metrics Comparison Report\n\n")
        file_handle.write(f"**Ontology 1**: {comparison_data.ontology1_name}  \n")
        file_handle.write(f"**Ontology 2**: {comparison_data.ontology2_name}  \n")
        file_handle.write(f"**Comparison Date**: {timestamp}\n\n")
        file_handle.write("---\n\n")
    
    def _write_executive_summary(self, file_handle, comparison_data: ComparisonData) -> None:
        """Write executive summary section
        
        Args:
            file_handle: Open file handle for writing
            comparison_data: ComparisonData object
        """
        summary = comparison_data.get_summary_statistics()
        characteristics_comparison = comparison_data.get_characteristics_comparison()
        
        # Get lists of improved and degraded characteristics
        improved_chars = [char for char, data in characteristics_comparison.items() 
                         if data['value']['difference'] > 0]
        degraded_chars = [char for char, data in characteristics_comparison.items() 
                         if data['value']['difference'] < 0]
        
        file_handle.write("## Executive Summary\n\n")
        file_handle.write(f"- **Metrics Improved**: {summary['metrics']['improved']} / {summary['metrics']['total']}\n")
        file_handle.write(f"- **Metrics Degraded**: {summary['metrics']['degraded']} / {summary['metrics']['total']}\n")
        file_handle.write(f"- **Metrics Unchanged**: {summary['metrics']['unchanged']} / {summary['metrics']['total']}\n")
        file_handle.write(f"- **Scaled Metrics Improved**: {summary['scaled_metrics']['improved']} / {summary['scaled_metrics']['total']}\n")
        file_handle.write(f"- **Scaled Metrics Degraded**: {summary['scaled_metrics']['degraded']} / {summary['scaled_metrics']['total']}\n")
        
        if improved_chars:
            file_handle.write(f"- **Characteristics Improved**: {', '.join(improved_chars)}\n")
        else:
            file_handle.write("- **Characteristics Improved**: None\n")
            
        if degraded_chars:
            file_handle.write(f"- **Characteristics Degraded**: {', '.join(degraded_chars)}\n")
        else:
            file_handle.write("- **Characteristics Degraded**: None\n")
        
        file_handle.write("\n---\n\n")
    
    def _write_characteristics_section(self, file_handle, comparison_data: ComparisonData) -> None:
        """Write characteristics comparison section with table
        
        Args:
            file_handle: Open file handle for writing
            comparison_data: ComparisonData object
        """
        characteristics_comparison = comparison_data.get_characteristics_comparison()
        
        file_handle.write("## Characteristics Comparison\n\n")
        file_handle.write("Comparison of the 6 main quality characteristics on a scale of 1 to 5.\n\n")
        
        # Add image
        img_name = f"{comparison_data.ontology1_name}_vs_{comparison_data.ontology2_name}_characteristics_comparison.png"
        file_handle.write(f"![Characteristics Comparison](img/{img_name})\n\n")
        
        # Add summary table
        file_handle.write("### Characteristics Summary Table\n\n")
        file_handle.write("| Characteristic | " + comparison_data.ontology1_name + " | " + 
                         comparison_data.ontology2_name + " | Difference | Change % | Status |\n")
        file_handle.write("|----------------|" + "-" * len(comparison_data.ontology1_name) + "|" +
                         "-" * len(comparison_data.ontology2_name) + "|------------|----------|--------|\n")
        
        for char_name, char_data in sorted(characteristics_comparison.items()):
            val1 = char_data['value'][comparison_data.ontology1_name]
            val2 = char_data['value'][comparison_data.ontology2_name]
            diff = char_data['value']['difference']
            percent = char_data['value']['percent_change']
            
            status = self._format_change_indicator(diff)
            percent_str = self._format_percent_change(percent)
            diff_str = f"{diff:+.2f}" if diff != 0 else "0.00"
            
            file_handle.write(f"| {char_name} | {val1:.2f} | {val2:.2f} | {diff_str} | {percent_str} | {status} |\n")
        
        file_handle.write("\n---\n\n")
    
    def _write_metrics_section(self, file_handle, comparison_data: ComparisonData) -> None:
        """Write metrics comparison section with tables
        
        Args:
            file_handle: Open file handle for writing
            comparison_data: ComparisonData object
        """
        metrics_comparison = comparison_data.get_metrics_comparison()
        scaled_metrics_comparison = comparison_data.get_scaled_metrics_comparison()
        
        file_handle.write("## Metrics Comparison\n\n")
        
        # Scaled metrics section
        file_handle.write("### Scaled Metrics (1-5 Scale)\n\n")
        img_name = f"{comparison_data.ontology1_name}_vs_{comparison_data.ontology2_name}_scaled_metrics_comparison.png"
        file_handle.write(f"![Scaled Metrics Comparison](img/{img_name})\n\n")
        
        # Raw metrics section
        file_handle.write("### Raw Metrics\n\n")
        img_name = f"{comparison_data.ontology1_name}_vs_{comparison_data.ontology2_name}_metrics_comparison.png"
        file_handle.write(f"![Metrics Comparison](img/{img_name})\n\n")
        
        # Metrics difference section
        file_handle.write("### Metrics Difference\n\n")
        file_handle.write("Shows the change in scaled metric values (positive = improvement).\n\n")
        img_name = f"{comparison_data.ontology1_name}_vs_{comparison_data.ontology2_name}_metrics_difference.png"
        file_handle.write(f"![Metrics Difference](img/{img_name})\n\n")
        
        # Metrics summary table
        file_handle.write("### Metrics Summary Table\n\n")
        file_handle.write("| Metric | " + comparison_data.ontology1_name + " | " + 
                         comparison_data.ontology2_name + " | Difference | Change % | Status |\n")
        file_handle.write("|--------|" + "-" * len(comparison_data.ontology1_name) + "|" +
                         "-" * len(comparison_data.ontology2_name) + "|------------|----------|--------|\n")
        
        for metric_name, metric_data in sorted(scaled_metrics_comparison.items()):
            val1 = metric_data[comparison_data.ontology1_name]
            val2 = metric_data[comparison_data.ontology2_name]
            diff = metric_data['difference']
            percent = metric_data['percent_change']
            
            status = self._format_change_indicator(diff)
            percent_str = self._format_percent_change(percent)
            diff_str = f"{diff:+.2f}" if diff != 0 else "0.00"
            
            file_handle.write(f"| {metric_name} | {val1:.2f} | {val2:.2f} | {diff_str} | {percent_str} | {status} |\n")
        
        file_handle.write("\n---\n\n")
    
    def _write_subcharacteristics_section(self, file_handle, comparison_data: ComparisonData) -> None:
        """Write subcharacteristics comparison section
        
        Args:
            file_handle: Open file handle for writing
            comparison_data: ComparisonData object
        """
        characteristics_comparison = comparison_data.get_characteristics_comparison()
        
        file_handle.write("## Subcharacteristics Comparison\n\n")
        file_handle.write("Detailed comparison of subcharacteristics for each of the 6 main characteristics.\n\n")
        
        for char_name in sorted(characteristics_comparison.keys()):
            file_handle.write(f"### {char_name}\n")
            img_name = f"{comparison_data.ontology1_name}_vs_{comparison_data.ontology2_name}_{char_name}_subcharacteristics_comparison.png"
            file_handle.write(f"![{char_name} Subcharacteristics](img/{img_name})\n\n")
        
        file_handle.write("---\n\n")
    
    def _write_key_findings(self, file_handle, comparison_data: ComparisonData) -> None:
        """Write key findings section with top improvements/degradations
        
        Args:
            file_handle: Open file handle for writing
            comparison_data: ComparisonData object
        """
        scaled_metrics_comparison = comparison_data.get_scaled_metrics_comparison()
        
        # Get top improvements and degradations
        improvements, degradations = self._get_top_changes(scaled_metrics_comparison, top_n=5)
        
        file_handle.write("## Key Findings\n\n")
        
        # Top improvements
        file_handle.write("### Top 5 Metric Improvements\n")
        if improvements:
            for i, (metric, diff, percent) in enumerate(improvements, 1):
                percent_str = self._format_percent_change(percent)
                file_handle.write(f"{i}. **{metric}**: +{diff:.2f} ({percent_str})\n")
        else:
            file_handle.write("No improvements found.\n")
        
        file_handle.write("\n")
        
        # Top degradations
        file_handle.write("### Top 5 Metric Degradations\n")
        if degradations:
            for i, (metric, diff, percent) in enumerate(degradations, 1):
                percent_str = self._format_percent_change(percent)
                file_handle.write(f"{i}. **{metric}**: {diff:.2f} ({percent_str})\n")
        else:
            file_handle.write("No degradations found.\n")
        
        file_handle.write("\n")
    
    def _get_top_changes(self, metrics_comparison: Dict[str, Dict[str, Any]], 
                        top_n: int = 5) -> Tuple[List[Tuple[str, float, float]], 
                                                 List[Tuple[str, float, float]]]:
        """Get top N improvements and degradations
        
        Args:
            metrics_comparison: Dictionary of metric comparisons
            top_n: Number of top changes to return
            
        Returns:
            Tuple of (improvements, degradations) lists, each containing
            (metric_name, difference, percent_change) tuples
        """
        improvements = []
        degradations = []
        
        for metric_name, metric_data in metrics_comparison.items():
            diff = metric_data['difference']
            percent = metric_data['percent_change']
            
            if diff > 0:
                improvements.append((metric_name, diff, percent))
            elif diff < 0:
                degradations.append((metric_name, diff, percent))
        
        # Sort by absolute difference
        improvements.sort(key=lambda x: x[1], reverse=True)
        degradations.sort(key=lambda x: abs(x[1]), reverse=True)
        
        return improvements[:top_n], degradations[:top_n]
    
    def _format_change_indicator(self, difference: float) -> str:
        """Format change value with emoji indicator
        
        Args:
            difference: The difference value
            
        Returns:
            Emoji indicator (✅/❌/➖)
        """
        if difference > 0:
            return "✅"
        elif difference < 0:
            return "❌"
        else:
            return "➖"
    
    def _format_percent_change(self, percent: float) -> str:
        """Format percent change with + or - sign
        
        Args:
            percent: The percent change value (can be None)
            
        Returns:
            Formatted string with sign or "N/A" if None
        """
        if percent is None:
            return "N/A"
        elif percent > 0:
            return f"+{percent:.2f}%"
        elif percent < 0:
            return f"{percent:.2f}%"
        else:
            return "0.00%"
    
    def generate_json_summary(self, comparison_data: ComparisonData, output_path: str) -> None:
        """Generate machine-readable JSON summary
        
        Args:
            comparison_data: ComparisonData object containing all comparison data
            output_path: Directory path where comparison_summary.json will be saved
        """
        summary = comparison_data.get_summary_statistics()
        metrics_comparison = comparison_data.get_metrics_comparison()
        scaled_metrics_comparison = comparison_data.get_scaled_metrics_comparison()
        characteristics_comparison = comparison_data.get_characteristics_comparison()
        
        # Build JSON structure
        json_data = {
            "ontology1": comparison_data.ontology1_name,
            "ontology2": comparison_data.ontology2_name,
            "timestamp": datetime.now().isoformat(),
            "summary": {
                "metrics_improved": summary['metrics']['improved'],
                "metrics_degraded": summary['metrics']['degraded'],
                "metrics_unchanged": summary['metrics']['unchanged'],
                "scaled_metrics_improved": summary['scaled_metrics']['improved'],
                "scaled_metrics_degraded": summary['scaled_metrics']['degraded'],
                "scaled_metrics_unchanged": summary['scaled_metrics']['unchanged'],
                "characteristics_improved": summary['characteristics']['improved'],
                "characteristics_degraded": summary['characteristics']['degraded'],
                "characteristics_unchanged": summary['characteristics']['unchanged'],
                "avg_metrics_change": summary['metrics']['avg_percent_change'],
                "avg_scaled_metrics_change": summary['scaled_metrics']['avg_percent_change'],
                "avg_characteristics_change": summary['characteristics']['avg_percent_change']
            },
            "metrics": metrics_comparison,
            "scaled_metrics": scaled_metrics_comparison,
            "characteristics": {}
        }
        
        # Add characteristics with simplified structure
        for char_name, char_data in characteristics_comparison.items():
            json_data["characteristics"][char_name] = {
                "value": char_data['value'],
                "subcharacteristics": char_data['subcharacteristics']
            }
        
        # Write JSON file
        json_path = f"{output_path}/comparison_summary.json"
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(json_data, f, indent=2, ensure_ascii=False)